### ISSUE TITLE
Barcode label is getting cut

### ISSUE THREAD

**Issue by ashishgehlot** [barnhill/barcodelib#100]
On Hight dpi system, barcode label is getting cut.

![image](https://user-images.githubusercontent.com/26749354/99935389-9b577600-2d86-11eb-81cf-b6016ecb6f4c.png)

On other system is generating like below (Expected):
![image](https://user-images.githubusercontent.com/26749354/99935552-f1c4b480-2d86-11eb-9801-0984ddde38c4.png)

**Comment by binki** [comment]
@ashishgehlot I do not think that BarcodeLib gives different results on a hiDPI system. I suspect the issue is outside of BarcodeLib. Do you have a sample of code which is causing the issue or instructions on how to reproduce this?

**Comment by ashishgehlot** [comment]
Hi @binki, Here is minimal sample built that I wanted to achieve. On High Dpi system(2k+ resolution)  label height increases and due to that barcode height reduce and become non-scannable. I am trying to add barcode on pdf. Its working fine on my system (1366*768) 96dpi. 

```
            // Generate Barcode Image
            Barcode barcode = new Barcode();
            barcode.IncludeLabel = true;
            barcode.Alignment = AlignmentPositions.CENTER;
            var barcodeImage = barcode.Encode(TYPE.CODE128A, "1234567890", System.Drawing.Color.Black, System.Drawing.Color.White, 160, 50);

```

**Comment by binki** [comment]
@ashishgehlot Based on the little information I have, it sounds like the issue is in the display layer of your application. It is probably something like this: you have set the image control in your GUI library to have a pixel-based size and you are trying to display the image as if it were 96DPI. The GUI library is doubling the size of the image when it displays which would work if you let the size of the image control itself also be doubled.

Are you able to share the GUI layer code responsible for displaying the image? Or are you able to take your question to some place more appropriate for support for your GUI library with the information I have provided to see if they have recommendations for you?

Unfortunately, this repository is not a place to get support for arbitrary GUI libraries. BarcodeLib simply generates a bitmap. How you render that bitmap is out of our control.

Thanks!

**Comment by ashishgehlot** [comment]
@binki Application is in WPF which is already DpiAware. Here is repository URL for reproduction (forgot to add).
In this application we are generating a barcode and stamping on pdf at particular location. Please have a look.

https://github.com/ashishgehlot/BarcodeStampDemo.git

**Comment by binki** [comment]
@ashishgehlot OK, after some investigation, I have found that this sort of is a gotcha in BarcodeLib. There is a workaround:

```csharp
barcode.LabelFont = new Font("Arial", 10 * 96f / 72, System.Drawing.FontStyle.Regular, GraphicsUnit.Pixel);
```

I am going to look into creating a PR which makes BarcodeLib behave consistently regardless of system DPI.

We probably haven’t noticed this before because the BarcodeStandardExample application is winforms and has DPI scaling disabled (so Windows makes it think the DPI is 96 and scales the application after it has drawn on screen).

**Comment by barnhill** [comment]
We should redo the example app in WPF and get it up to this century :)

**Comment by binki** [comment]
@barnhill 
> We should redo the example app in WPF and get it up to this century :)

Hehe. I actually have more experience with winforms (and still not all that much experience with it). It *is* possible to make winforms opt into DPI scaling and even multi-monitor DPI support (which is what keeps applications from going blurry), but it is certainly much cleaner with WPF.

**Comment by ashishgehlot** [comment]
Hi, For workaround, I have disabled HighDpiAwerness by adding App.Manifest file. It worked for me at least.

```
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" >
 ...
  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>false</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
 ...
</assembly>
```

**Comment by binki** [comment]
@ashishgehlot Yes, that is a way to work around the issue. It is unfortunate because it means your application will appear blurry for users. I think you should prefer the code work around I suggested. However, that is up to you ;-).

We will still be updating BarcodeLib so that this issue won’t happen for future users :-).

Thanks for the report!
