### ISSUE TITLE
Could it support GS1 128 / EAN128??

### ISSUE THREAD

**Issue by rangiorabakery** [barnhill/barcodelib#136]
Could it support GS1 128 / EAN128?

**Comment by Mike-Inasolve** [comment]
Hi Brad, 
The Barcodelib is very handy and efficient, love it.

I am having an urgent issue and would appreciate it if you could please assist with some insight.
I am trying to print with GS1-128 barcodes though, it seems that the lib doesn't like barcodes with a length > 25 characters otherwise the barcode is blank.

I'm using this to product GS1 SSCC labels and the SCC label could be a value like (02)19300633184053(37)72(13)221114(10)295410 but the library won't display the barcode unless I cut it back to 24 characters like this (02)19300633184053(37)72

For GS1-128 standard, the barcode should look like the one below (generated via a tool):
![image](https://user-images.githubusercontent.com/43563578/202587507-ebee7927-9bbd-4fe4-b437-48b404f1738b.png)

Assembly versions we are using:
![image](https://user-images.githubusercontent.com/43563578/202587632-32f0cc64-0709-42f0-9e63-cebc25318f2f.png)
![image](https://user-images.githubusercontent.com/43563578/202587685-507ad608-38e2-483b-9b6e-ae9ac58d73bb.png)

**Comment by binki** [comment]
@Mike-Inasolve  What width are you using for the barcode? You need to make sure that your image width is at least 500px or so for a barcode that long. In the image generated with a tool, the bar width is thinner than a pixel, so the tool you used generated an image with an unscannable barcode.

If you use an updated version of BarcodeLib from NuGet, you would get a clear error/exception.

If you are still having an issue, please consider opening a new issue as I think it is unrelated to this issue.

**Comment by binki** [comment]
@barnhill is this the original comment’s issue addressed? It sounds like they just need to know to use Code128, so this issue could be closed since their question was answered. Am I missing something?

**Comment by Mike-Inasolve** [comment]
Hi Nathan,

Using the barcodelib from SSRS as an assembly reference.
Works for all other barcodes except the SCC barcodes, doesn’t seem to like anything more than 24 or so chars.

However, we compiled our own DLL and generated the barcodes perfectly fine using the barcode lib so it appears to be an issue in SSRS. We now generate the barcode as a byte array and store it in the db and just pull the bytes when we run the ssrs report instead of generating at runtime and this is working nicely.

Kind Regards,
Mike

**Comment by barnhill** [comment]
Are y'all ok closing as not an issue?

**Comment by Mike-Inasolve** [comment]
Sure, thanks for following up 👍


Kind Regards,
Mike

________________________________

**Comment by barnhill** [comment]
Closing as addressed
