### ISSUE TITLE
Could not install package 'BarcodeLib 2.2.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author

### ISSUE THREAD

**Issue by MrArif-5** [barnhill/barcodelib#86]
![Screenshot (11)](https://user-images.githubusercontent.com/57086628/79261210-1f6e8480-7ead-11ea-89bc-47a24e1fc577.png)

am trying more time it was display version issue vs2017 using while adding DLL from ManageNuget pakkage Brad Barnhill please give me solution

**Comment by binki** [comment]
Hi @MrArif-5 

BarcodeLib-2.0.0 and newer require NETStandard-2.0. You are targeting .NET 4.5.2 which, according to, https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support , is not *fully* supported until .NET 4.7.2. You have two options and you must choose one based on your situation. If possible, the first choice is preferred because it will have you running the latest software with new features and bug fixes:

1. Retarget your project. Right-click on your project in Solution Explorer, choose Properties, choose Application on the left sidebar of the property page, and under Target Framework choose .NET Framework 4.7.1. You will be prompted to reload your project. You should now be able to install and use the latest version of BarcodeLib.

![Retargeting to .NET Framework 4.7.1 which supports the latest BarcodeLib](https://user-images.githubusercontent.com/82626/79264183-21f7bc80-7e62-11ea-9a98-e7c914a014d9.png)


2. Use an older version of BarcodeLib which supports your framework version. It will have fewer features and may have bugs which have been addressed in later versions. To do this, open the NuGet Package Manager by right-clicking on your project in Solution Explorer and choose “Manage NuGet Packages”. Select the Browse tab and in Search enter BarcodeLib. Select it in the left pane. Then, in the right pane, use the version dropdown to select 1.3.0. Then click Install in the right pane:

![installing BarcodeLib-1.3.0 which supports older versions of .NET Framework](https://user-images.githubusercontent.com/82626/79264104-01c7fd80-7e62-11ea-83f4-84589afb371f.png)

**Comment by MrArif-5** [comment]
yes issue resolve am following your instruction Brad Barnhill, Thank You
