### ISSUE TITLE
Which default font is used to display barcode label ?

### ISSUE THREAD

**Issue by ashishgehlot** [barnhill/barcodelib#99]
![test](https://user-images.githubusercontent.com/26749354/98776152-7244f600-2414-11eb-9e62-435ffafb8f52.png)

Which font is used to display label ? If its Arial then note small tale after digit 4 (from MS word). This tale is missing in barcode image attached above.   
![image](https://user-images.githubusercontent.com/26749354/98776377-d10a6f80-2414-11eb-9aef-db797f5d95e1.png)

**Comment by barnhill** [comment]
Did you figure it out?

**Comment by binki** [comment]
That font is Microsoft Sans Serif, Bold, rendered at 13.3333px. It also should have a tail on the 4, but due to it being rendered without smoothing to keep the text looking sharp, that tail probably gets cut off.

If I force the font size to be one pixel bigger in the debugger, you can start seeing that tail:

![barcode with 4 showing a tail](https://user-images.githubusercontent.com/82626/100050048-a510c600-2de6-11eb-8246-fbb178920573.png)
